name: flutter_place_picker
description: A Flutter plugin which provides 'Picking Places' using OpenStreet, Here Maps and Google Maps.
version: 0.0.1-dev.5
homepage: https://github.com/saytoonz/flutter_place_picker

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  provider: ^6.0.5
  flutter_google_maps_webservices: ^1.1.1
  google_api_headers: ^4.2.0
  tuple: ^2.0.1
  dio: ^5.0.2
  http: ^1.2.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
